[tool.mypy]
mypy_path = "$MYPY_CONFIG_FILE_DIR/mypy_stubs"
python_version = "3.13"

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "C90",
    "D",
    "EM",
    "FBT",
    "INP",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PT",
    "PTH",
    "PYI025",
    "S",
    "T20",
    "TRY003",
    "TRY004",
]

[tool.pyright]
exclude = [
    "**/.*",
    "bazel-*",
    "tests/other_workspace/bazel-*",
    "target",
]
