load("//tools/shell:defs.bzl", "sh_source")

sh_source(
    name = "container_build",
    src = "container_build.sh",
    visibility = ["//visibility:private"],
)

sh_source(
    name = "container_shell",
    src = "container_shell.sh",
    visibility = ["//visibility:private"],
)

sh_source(
    name = "container_test",
    src = "container_test.sh",
    visibility = ["//visibility:private"],
)

sh_source(
    name = "extra_precommit",
    src = "extra_precommit.sh",
    visibility = ["//:__pkg__"],
)
