load("//tools/shell:defs.bzl", "sh_source")

sh_source(
    name = "run_tests",
    src = "run_tests.sh",
    visibility = ["//visibility:private"],
)

sh_source(
    name = "setup_tests",
    src = "setup_tests.sh",
    visibility = ["//visibility:private"],
)
