[package]
name = "markdown_private_group"
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "group_publications"
path = "group_publications.rs"

[dependencies]
clap.workspace = true
html-escape.workspace = true
markdown.workspace = true
